name <- readline(prompt = "Please enter your name: ")
age <- readline(prompt = "Please enter your age: ")
cat("Your name is:", name, "\n")
cat("Your age is:", age, "\n")
cat("You are using R version:", R.version$version.string, "\n")
